---
- name: Check input parameter
  ansible.builtin.assert:
    that:
      - (aas_id is defined) and (aas_id | length > 0)

- name: Create AAS
  ansible.builtin.uri:
    url: "{{ aas_server_base_url }}/shells/{{ aas_id }}"
    method: PUT
    headers:
      Content-Type: application/json
    body_format: json
    body: "{{ aas }}"
  register: create_aas_request
  when: force_create_ass | default(false)
  delegate_to: localhost

- name: Create Webcams Submodel
  ansible.builtin.uri:
    url: "{{ aas_server_base_url }}/shells/{{ aas_id }}/aas/submodels/{{aas_submodel.idShort}}"
    method: PUT
    headers:
      Content-Type: application/json
    body_format: json
    body: "{{ aas_submodel }}"
  delegate_to: localhost

- name: Create Submodel Element Collections
  ansible.builtin.include_tasks: register_submodel_element_collection.yml
  loop: "{{ webcams }}"